<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27750" started-at="2019-09-08T12:49:32Z" finished-at="2019-09-08T12:50:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27750" started-at="2019-09-08T12:49:32Z" finished-at="2019-09-08T12:50:00Z">
      <class name="comm.learnautomation.testcases.LogInTestCrm">
        <test-method status="PASS" signature="setup()[pri:0, instance:comm.learnautomation.testcases.LogInTestCrm@5ba23b66]" name="setup" is-config="true" duration-ms="22629" started-at="2019-09-08T08:49:32Z" finished-at="2019-09-08T08:49:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="loginApp()[pri:0, instance:comm.learnautomation.testcases.LogInTestCrm@5ba23b66]" name="loginApp" duration-ms="1469" started-at="2019-09-08T08:49:55Z" finished-at="2019-09-08T08:49:56Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at comm.learnautomation.utility.ExcelDataProvider.getStringData(ExcelDataProvider.java:24)
	at comm.learnautomation.testcases.LogInTestCrm.loginApp(LogInTestCrm.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginApp -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:comm.learnautomation.testcases.LogInTestCrm@5ba23b66]" name="teardown" is-config="true" duration-ms="3612" started-at="2019-09-08T08:49:56Z" finished-at="2019-09-08T08:50:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- comm.learnautomation.testcases.LogInTestCrm -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
